### ISSUE TITLE
Error in "Read data" 

### ISSUE THREAD

**Issue by ClemensLinnhoff** [eclipse/openmcx#11]
Sometimes, I get an error during "Read data" when starting a co-simulation.
If I just run openmcx again, the error does not appear anymore.
It seems to have something to do with the temporary export of the FMUs. It also does not appear, if I delete the temp folder before every simulation run.

```
ERROR: my_fmu: Cannot create /home/clemens/Repos/openmcx/temp/my_fmu_9f625610ad7d12446114c82df51b1de6 to unpack examples/my_example/resources/my_fmu.fmu
ERROR: my_fmu: Could not open FMU
ERROR: Model: Could not read specific data of element my_fmu
ERROR: Model: Reading elements failed
```

However, it appears quite often.
Any idea, where this is coming from?

**Comment by klausschuch** [comment]
By default openmcx extracts an FMU in a temp folder in the current working directory and deletes this directory after the simulation. The name of the folder is composed of the name of the FMU (within the ssd file, "my_fmu" in your example) and the md5 hash of the FMU.
Hence, if the FMU doesn't change, openmcx uses the very same folder name for each simulation run.

It seems that these temp directories didn't get deleted in your case.
I guess the openmcx process either crashes before deleting the files or some files/directories couldn't be deleted because some other process (a virus scanner maybe) was locking the files/directories.

No timestamp or so is added to the folder because we didn't want to pollute the hard disc with extracted files for each simulation run. With the given error we wanted to inform the user that previous runs were not completed as expected.

You could set the command line option --verbose, this should give you a log message for each file/directory that couldn't be deleted (only implemented on windows). We should maybe add these messages as warning messages in the normal simulation.log file.

**Comment by ClemensLinnhoff** [comment]
I often stop the simulation with Ctrl + C in the console. This might explain, why the tmp folders are not deleted. Would it be possible to implement, that the tmp folder is deleted before every simulation run? This would solve the issue from my point of view.

**Comment by klausschuch** [comment]
The requested Ctrl + C mechanism is already implemented (see [signals.c](https://github.com/eclipse/openmcx/blob/6030982d72721460acc81d6fa2798cde7a09d855/src/util/common/signals.c#L28))
You should see "Caught Ctrl-C. Stopping." in the log file and then openmcx shuts down just like as if the simulation end time was reached.
BUT if you hit Ctrl + C more than once, we kill the process and you should see "Caught Ctrl-C again. Exiting." in the log file and now the temp files are not deleted anymore.

**Comment by ClemensLinnhoff** [comment]
You are right! I didn't realize that. I just need to get rid of my habit to always hit Ctrl + C multiple times.
Thanks!
